### ISSUE TITLE
Reactive Example

### ISSUE THREAD

**Issue by zachariahyoung** [gregturn/draft-tut-react-and-spring-data-rest#5]
Greg,

Would it be possible to include a small reactive example?  Maybe we could include a department entity to the employee class.  It would just include department name and id.  It would have it's own Spring Data rest repository.  Employee repository would only return the link back to the department.  Then in the front project include a method in the Application controller to return a list of employees sorted by the department name.

I can complete the part I know about in a pull request if that helps.

Thanks

Zach

**Comment by gregturn** [comment]
@zachariahyoung Let's debate that after I publish the series. The plan is to bundle the whole thing together into a tutorial, so I need to think if that would fit that plan. I also plan to upgrade the JS to ES6 since it's the future.

**Comment by gregturn** [comment]
I'm closing this issue since everything has moved to https://github.com/spring-guides/tut-react-and-spring-data-rest. 

Feel free to read the tutorial and open new issues there.
