### ISSUE TITLE
404 on JSXTransformer

### ISSUE THREAD

**Issue by SingleShot** [gregturn/draft-tut-react-and-spring-data-rest#6]
Thanks for this tutorial. I freshly cloned the project and built/ran part 1 (basic). Unfortunately it fails when navigating to http://localhost:8080:

    GET http://localhost:8080/bower_components/react/JSXTransformer.js
    Uncaught Error: Script error for: JSXTransformer/JSXTransformer

Searching around it appears JSXTransformer is deprecated but I'm not sure if that is the problem or not.

**Comment by SingleShot** [comment]
The fix is to lock down the version of react In `bower.json` to 0.13.3 by adding it to the list of dependencies:

    "dependencies": {
      "requirejs": "~2.1.20",
      "rest": "~1.3.1",
      "requirejs-react-jsx": "~0.14.2",
      "react": "0.13.3"
    }

**Comment by gregturn** [comment]
Transitive dependency snafu? If so, the will be overcome when I upgrade to webpack + Babel.

**Comment by muks2048** [comment]
Hi Greg, thanks for the awesome blog about react and Spring Data  REST, however I'm getting a javascript error when I try to run the second tutorial about Hypermedia, and the table does not display any record when rendered in the browser. The error message says:
TypeError: employeeCollection.entity._links.profile is undefined
Kindly help me overcome this, so I can continue to the rest of the tutorials.
Thanks in advance!

**Comment by gregturn** [comment]
@muks2048 are you experiencing the same issue as described at the top of this ticket? If not, can you open a new one and provide some more details? Thanks.

**Comment by Yolgie** [comment]
I am still experiencing the problem with the current version (3c72f5b39bad34025ab522511c75a833c05f3f14)

```
Failed to load resource: the server responded with a status of 404 (Not Found) :8080/bower_components/requirejs/require.js:140 Uncaught Error: Script error for "JSXTransformer/JSXTransformer"
http://requirejs.org/docs/errors.html#scripterror
:8080/bower_components/requirejs/require.js:140 Uncaught Error: Load timeout for modules: jsx/jsx!app_unnormalized2,jsx/jsx!app
http://requirejs.org/docs/errors.html#timeout
```

With an unchanged pagesourcec
```
<!DOCTYPE html>

<html>
<head lang="en">
    <meta charset="UTF-8" />
    <title>ReactJS + Spring Data REST</title>
    <script async="" data-main="/run.js" src="/bower_components/requirejs/require.js"></script>
    <link rel="stylesheet" href="/main.css" />
</head>
<body>

    <div id="react"></div>

</body>
</html>
```

**Comment by gregturn** [comment]
Entire code base moved to https://github.com/spring-guides/tut-react-and-spring-data-rest and upgraded to webpack, Babel.js, and ES6.

**Comment by kopax** [comment]
The latest react version of this tutorial is on react 0.13.3 while the latest production ready react version is 15.3.2.

Updating in this [project](https://github.com/spring-guides/tut-react-and-spring-data-rest/) the file [package.json](https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/src/main/resources/static/package.json) the version will result to the same issue.
