### ISSUE TITLE
UI comes up empty (the react piece i think)

### ISSUE THREAD

**Issue by mddanese** [gregturn/draft-tut-react-and-spring-data-rest#9]
Ok, I see this issue has already been reported, trying the suggestions therein. Sorry did not catch that earlier, please close this issue.
thx.

First off, really nice, extensive demo - time and care is evident, thx.

Pulled the code into eclipse via github, runs under springboot, very quick setup. 
Issue for me - the ui doesn't render (except the html 'login' button, which works fine w usr/pswd entered). (http://localhost:8080) I do have node installed on my mac. Is there an issue related to 'jsx'?  Any tips?

**Comment by gregturn** [comment]
Thanks.

The code that started here has been published and updated many times here => https://github.com/spring-guides/tut-react-and-spring-data-rest

Many improvements including things like webpack, Spring Boot upgrades, etc.

Also see the tutorial here => https://spring.io/guides/tutorials/react-and-spring-data-rest/
